# Generated by Django 2.1.5 on 2022-02-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='nsfw',
        ),
    ]
